package com.playmonumenta.plugins.depths.charmfactory;

import com.playmonumenta.plugins.depths.DepthsTree;
import javax.annotation.Nullable;

public enum CharmAdjectives {

	ICY("Icy", DepthsTree.FROSTBORN),
	HEAVY("Heavy", DepthsTree.EARTHBOUND),
	RADIANT("Radiant", DepthsTree.DAWNBRINGER),
	PULSING("Pulsing", DepthsTree.SHADOWDANCER),
	EERIE("Eerie", DepthsTree.SHADOWDANCER),
	BLEAK("Bleak", DepthsTree.SHADOWDANCER),
	SHADOWED("Shadowed", DepthsTree.SHADOWDANCER),
	UMBRAL("Umbral", DepthsTree.SHADOWDANCER),
	TUMULTUOUS("Tumultuous", DepthsTree.WINDWALKER),
	SWIRLING("Swirling", DepthsTree.WINDWALKER),
	BRISK("Brisk", DepthsTree.WINDWALKER),
	WILD("Wild", DepthsTree.WINDWALKER),
	FLOWING("Flowing", DepthsTree.WINDWALKER),
	RAUCOUS("Raucous", DepthsTree.FLAMECALLER),
	IRASCIBLE("Irascible", DepthsTree.FLAMECALLER),
	BLOODY("Bloody", DepthsTree.FLAMECALLER),
	BURNISHED("Burnished", DepthsTree.FLAMECALLER),
	BURNING("Burning", DepthsTree.FLAMECALLER),
	SCORCHED("Scorched", DepthsTree.FLAMECALLER),
	BITTER("Bitter", DepthsTree.FROSTBORN),
	FRIGID("Frigid", DepthsTree.FROSTBORN),
	BOREAL("Boreal", DepthsTree.FROSTBORN),
	POLAR("Polar", DepthsTree.FROSTBORN),
	CRISP("Crisp", DepthsTree.FROSTBORN),
	ROBUST("Robust", DepthsTree.EARTHBOUND),
	STUDY("Study", DepthsTree.EARTHBOUND),
	RUGGED("Rugged", DepthsTree.EARTHBOUND),
	VITAL("Vital", DepthsTree.EARTHBOUND),
	STOUT("Stout", DepthsTree.EARTHBOUND),
	HONORABLE("Honorable", DepthsTree.DAWNBRINGER),
	BRIGHT("Bright", DepthsTree.DAWNBRINGER),
	SHINING("Shining", DepthsTree.DAWNBRINGER),
	GLEAMING("Gleaming", DepthsTree.DAWNBRINGER),
	CLEAR("Clear", DepthsTree.DAWNBRINGER),
	BRUTAL("Brutal", DepthsTree.STEELSAGE),
	HARDENED("Hardened", DepthsTree.STEELSAGE),
	RUTHLESS("Ruthless", DepthsTree.STEELSAGE),
	SHARP("Sharp", DepthsTree.STEELSAGE),
	JOSHUAS("Joshua's", null),
	ARDENT("Ardent", DepthsTree.FLAMECALLER),
	BLAZING("Blazing", DepthsTree.FLAMECALLER),
	BOILING("Boiling", DepthsTree.FLAMECALLER),
	INCANDESCENT("Incandescent", DepthsTree.FLAMECALLER),
	CANDENT("Candent", DepthsTree.FLAMECALLER),
	FERVENT("Fervent", DepthsTree.FLAMECALLER),
	SIZZLING("Sizzling", DepthsTree.FLAMECALLER),
	TORRID("Torrid", DepthsTree.FLAMECALLER),
	INFERNAL("Infernal", DepthsTree.FLAMECALLER),
	SMOKY("Smoky", DepthsTree.FLAMECALLER),
	STEAMING("Steaming", DepthsTree.FLAMECALLER),
	CLOUDY("Cloudy", DepthsTree.SHADOWDANCER),
	MISTY("Misty", DepthsTree.SHADOWDANCER),
	MURKY("Murky", DepthsTree.SHADOWDANCER),
	GRAVE("Grave", DepthsTree.SHADOWDANCER),
	DISMAL("Dismal", DepthsTree.SHADOWDANCER),
	PERILOUS("Perilous", DepthsTree.SHADOWDANCER),
	GRIM("Grim", DepthsTree.SHADOWDANCER),
	NIGHTMARISH("Nightmarish", DepthsTree.SHADOWDANCER),
	CRYPTIC("Cryptic", DepthsTree.SHADOWDANCER),
	BRILLIANT("Brilliant", DepthsTree.DAWNBRINGER),
	DAZZLING("Dazzling", DepthsTree.DAWNBRINGER),
	GLORIOUS("Glorious", DepthsTree.DAWNBRINGER),
	GRACIOUS("Gracious", DepthsTree.DAWNBRINGER),
	SUPERB("Superb", DepthsTree.DAWNBRINGER),
	STUNNING("Stunning", DepthsTree.DAWNBRINGER),
	SUNNY("Sunny", DepthsTree.DAWNBRINGER),
	MUNIFICENT("Munificent", DepthsTree.DAWNBRINGER),
	LUMINOUS("Luminous", DepthsTree.DAWNBRINGER),
	LAMBENT("Lambent", DepthsTree.DAWNBRINGER),
	BLUSTERY("Blustery", DepthsTree.WINDWALKER),
	GUSTY("Gusty", DepthsTree.WINDWALKER),
	STORMY("Stormy", DepthsTree.WINDWALKER),
	BREEZY("Breezy", DepthsTree.WINDWALKER),
	SWIFT("Swift", DepthsTree.WINDWALKER),
	ALACRITOUS("Alacritous", DepthsTree.WINDWALKER),
	FLEET("Fleet", DepthsTree.WINDWALKER),
	NIMBLE("Nimble", DepthsTree.WINDWALKER),
	RAPID("Rapid", DepthsTree.WINDWALKER),
	WINGED("Winged", DepthsTree.WINDWALKER),
	TOUGH("Tough", DepthsTree.EARTHBOUND),
	STRONG("Strong", DepthsTree.EARTHBOUND),
	RUSTIC("Rustic", DepthsTree.EARTHBOUND),
	CRUSHING("Crushing", DepthsTree.EARTHBOUND),
	THICK("Thick", DepthsTree.EARTHBOUND),
	MUDDY("Muddy", DepthsTree.EARTHBOUND),
	DENSE("Dense", DepthsTree.EARTHBOUND),
	HEFTY("Hefty", DepthsTree.EARTHBOUND),
	IRON("Iron", DepthsTree.STEELSAGE),
	METALLIC("Metallic", DepthsTree.STEELSAGE),
	PROFICIENT("Proficient", DepthsTree.STEELSAGE),
	PRECISE("Precise", DepthsTree.STEELSAGE),
	ACCURATE("Accurate", DepthsTree.STEELSAGE),
	ACUTE("Acute", DepthsTree.STEELSAGE),
	POINTED("Pointed", DepthsTree.STEELSAGE),
	GRITTY("Gritty", DepthsTree.STEELSAGE),
	ARCTIC("Arctic", DepthsTree.FROSTBORN),
	GLACIAL("Glacial", DepthsTree.FROSTBORN),
	FREEZING("Freezing", DepthsTree.FROSTBORN),
	CRYOGENIC("Cryogenic", DepthsTree.FROSTBORN),
	FRAGILE("Fragile", DepthsTree.FROSTBORN),
	POWDERED("Powdered", DepthsTree.FROSTBORN),
	MELTING("Melting", DepthsTree.FROSTBORN),
	REFLECTIVE("Reflective", DepthsTree.FROSTBORN),
	HEROIC("Heroic", null),
	MAJESTIC("Majestic", null),
	MYTHIC("Mythic", null),
	CELESTIAL("Celestial", null),
	ASTRAL("Astral", null),
	MITTENS("Mittens'", null),
	GARRULOUS("Garrulous", null),
	SUBLIME("Sublime", null);



	public final String mName;
	public final @Nullable DepthsTree mTree;

	CharmAdjectives(String name, @Nullable DepthsTree tree) {
		mName = name;
		mTree = tree;
	}
}
