package com.playmonumenta.plugins.utils;

import java.util.ArrayList;
import java.util.List;

import org.bukkit.Bukkit;
import org.bukkit.ChatColor;
import org.bukkit.GameMode;
import org.bukkit.Location;
import org.bukkit.Material;
import org.bukkit.attribute.Attribute;
import org.bukkit.entity.Player;
import org.bukkit.potion.PotionEffect;
import org.bukkit.potion.PotionEffectType;
import org.bukkit.util.Vector;

import com.playmonumenta.plugins.Plugin;
import com.playmonumenta.plugins.classes.Spells;
import com.playmonumenta.plugins.classes.magic.AbilityCastEvent;
import com.playmonumenta.plugins.potion.PotionManager.PotionID;

public class PlayerUtils {
	public static boolean isCritical(Player player) {
		return player.getFallDistance() > 0.0F &&
		       !player.isOnGround() &&
		       !player.isInsideVehicle() &&
		       !player.hasPotionEffect(PotionEffectType.BLINDNESS) &&
		       player.getLocation().getBlock().getType() != Material.LADDER &&
		       player.getLocation().getBlock().getType() != Material.VINE;
	}

	public static void callAbilityCastEvent(Player player, Spells spell) {
		AbilityCastEvent event = new AbilityCastEvent(player, spell);
		Bukkit.getPluginManager().callEvent(event);
	}

	public static void awardStrike(Plugin plugin, Player player, String reason) {
		int strikes = ScoreboardUtils.getScoreboardValue(player, "Strikes");
		strikes++;
		ScoreboardUtils.setScoreboardValue(player, "Strikes", strikes);

		Location loc = player.getLocation();
		String OOBLoc = "[" + (int)loc.getX() + ", " + (int)loc.getY() + ", " + (int)loc.getZ() + "]";

		player.sendMessage(ChatColor.RED + "WARNING: " + reason);
		player.sendMessage(ChatColor.RED + "Location: " + OOBLoc);
		player.sendMessage(ChatColor.YELLOW + "This is an automated message generated by breaking a game rule.");
		player.sendMessage(ChatColor.YELLOW + "You have been teleported to spawn and given slowness for 5 minutes.");
		player.sendMessage(ChatColor.YELLOW + "There is no further punishment, but please do follow the rules.");

		plugin.mPotionManager.addPotion(player, PotionID.APPLIED_POTION,
		                                new PotionEffect(PotionEffectType.SLOW, 5 * 20 * 60, 3, false, true));

		player.teleport(player.getWorld().getSpawnLocation());
	}

	public static List<Player> getNearbyPlayers(Player player, double radius, boolean includeSourcePlayer) {
		List<Player> players = getNearbyPlayers(player.getLocation(), radius);
		if (!includeSourcePlayer) {
			players.removeIf(p -> (p == player));
		} else {
			if (!players.contains(player)) {
				players.add(player);
			}
		}
		return players;
	}

	public static List<Player> getNearbyPlayers(Location loc, double radius) {
		List<Player> players = new ArrayList<Player>();

		for (Player player : Bukkit.getOnlinePlayers()) {
			if (loc.distance(player.getLocation()) <= radius && player.getGameMode() != GameMode.SPECTATOR
			    && !player.hasMetadata("CloakAndDaggerPlayerIsInvisible")) {
				players.add(player);
			}
		}

		return players;
	}

	public static void healPlayer(Player player, double healAmount) {
		if (!player.isDead()) {
			double newHealth = Math.min(player.getHealth() + healAmount, player.getAttribute(Attribute.GENERIC_MAX_HEALTH).getValue());
			player.setHealth(newHealth);
		}
	}

	public static Location getRightSide(Location location, double distance) {
		float angle = location.getYaw() / 60;
		return location.clone().subtract(new Vector(Math.cos(angle), 0, Math.sin(angle)).normalize().multiply(distance));
	}

}
