package pe.bossfights.spells;

import org.bukkit.entity.LivingEntity;
import org.bukkit.entity.Player;
import org.bukkit.Location;
import org.bukkit.Particle;
import org.bukkit.plugin.Plugin;
import org.bukkit.potion.PotionEffect;
import org.bukkit.potion.PotionEffectType;
import org.bukkit.Sound;

public class SpellViriusLaser extends BaseLaser
{
	public SpellViriusLaser(Plugin plugin, LivingEntity boss, int detectionRange)
	{
		super(plugin, boss, detectionRange, 100, false, false,
		      // Tick action per player
		      (Player player, int ticks, boolean blocked) ->
		        {
		            player.playSound(player.getLocation(), Sound.UI_TOAST_IN, 2, (0.5f + ((float)ticks / 80f) * 1.5f));
		            boss.getLocation().getWorld().playSound(boss.getLocation(), Sound.UI_TOAST_IN, 2, (0.5f + ((float)ticks / 80f) * 1.5f));
					if (ticks == 0)
						boss.addPotionEffect(new PotionEffect(PotionEffectType.SLOW, 110, 4), true);
		        },
		      // Particles generated by the laser
		      (Location loc) ->
		        {
		            loc.getWorld().spawnParticle(Particle.CLOUD, loc, 1, 0.02, 0.02, 0.02, 0);
		            loc.getWorld().spawnParticle(Particle.WATER_SPLASH, loc, 1, 0.04, 0.04, 0.04, 1);
		        },
		      // Damage generated at the end of the attack
		      (Player player, Location loc, boolean blocked) ->
		        {
		            loc.getWorld().playSound(loc, Sound.ENTITY_ENDERDRAGON_FIREBALL_EXPLODE, 1f, 1.5f);
		            loc.getWorld().spawnParticle(Particle.WATER_WAKE, loc, 300, 0.8, 0.8, 0.8, 0);
					if (!blocked)
						player.damage(16f);
		        });
	}
}
