package pe.bossfights.spells;

import org.bukkit.Bukkit;
import org.bukkit.entity.Entity;
import org.bukkit.entity.Player;
import org.bukkit.Location;
import org.bukkit.Particle;
import org.bukkit.plugin.Plugin;
import org.bukkit.Sound;

public class SpellAxtalDeathRay extends BaseLaser
{
	public SpellAxtalDeathRay(Plugin plugin, Entity boss)
	{
		super(plugin, boss, 60, 140, false, true,
		      // Tick action per player
		      (Player player, int ticks, boolean blocked) ->
		        {
		            player.playSound(player.getLocation(), Sound.UI_TOAST_IN, 2, (0.5f + ((float)ticks / 100f) * 1.5f));
		            boss.getLocation().getWorld().playSound(boss.getLocation(), Sound.UI_TOAST_IN, 2, (0.5f + ((float)ticks / 100f) * 1.5f));
		            player.playSound(player.getLocation(), Sound.ENTITY_WITHER_SPAWN, 2, (0.5f + ((float)ticks / 100f) * 1.5f));
		            boss.getLocation().getWorld().playSound(boss.getLocation(), Sound.UI_TOAST_IN, 2, (0.5f + ((float)ticks / 100f) * 1.5f));
		        },
		      // Particles generated by the laser
		      (Location loc) ->
		        {
		            loc.getWorld().spawnParticle(Particle.SMOKE_NORMAL, loc, 1, 0.02, 0.02, 0.02, 0);
		            loc.getWorld().spawnParticle(Particle.SMOKE_LARGE, loc, 1, 0.02, 0.02, 0.02, 0);
		            loc.getWorld().spawnParticle(Particle.SPELL_MOB, loc, 1, 0.02, 0.02, 0.02, 1);
		        },
		      // TNT generated at the end of the attack
		      (Player player, Location loc, boolean blocked) ->
		        {
		            Bukkit.getServer().dispatchCommand(Bukkit.getConsoleSender(), "summon tnt " + loc.getX() + " " + loc.getY() + " " + loc.getZ() + " {Fuse:1}");
		            Bukkit.getServer().dispatchCommand(Bukkit.getConsoleSender(), "summon tnt " + loc.getX() + " " + loc.getY() + " " + loc.getZ() + " {Fuse:3}");
		            Bukkit.getServer().dispatchCommand(Bukkit.getConsoleSender(), "summon tnt " + loc.getX() + " " + loc.getY() + " " + loc.getZ() + " {Fuse:5}");
		        });
	}
}
