package pe.bossfights.spells;

import org.bukkit.entity.Entity;
import org.bukkit.entity.Player;
import org.bukkit.Location;
import org.bukkit.Particle;
import org.bukkit.plugin.Plugin;
import org.bukkit.Sound;

public class SpellMaskedEldritchBeam extends BaseLaser
{
	public SpellMaskedEldritchBeam(Plugin plugin, Entity boss)
	{
		super(plugin, boss, 40, 120, true, false,
		      // Tick action per player
		      (Player player, int ticks, boolean blocked) ->
		        {
		            player.playSound(player.getLocation(), Sound.UI_TOAST_IN, 2, (0.5f + ((float)ticks / 80f) * 1.5f));
		            boss.getLocation().getWorld().playSound(boss.getLocation(), Sound.UI_TOAST_IN, 2, (0.5f + ((float)ticks / 80f) * 1.5f));
		            if (!blocked && ticks > 0 && ((ticks % 20) == 0))
		                player.damage(3f);
		        },
		        // Particles generated by the laser
		      (Location loc) ->
		        {
		            loc.getWorld().spawnParticle(Particle.CLOUD, loc, 1, 0.02, 0.02, 0.02, 0);
		            loc.getWorld().spawnParticle(Particle.SPELL_MOB, loc, 1, 0.02, 0.02, 0.02, 1);
		        },
		      null);
	}
}
