package pe.project.network.packet;

import pe.project.Plugin;
import pe.project.utils.PacketUtils;

public class ForwardErrorPacket implements Packet {

	// TODO - Ugh, this is so annoying
	// Want to just be able to call TransferPlayerDataPacket.getPacketChannel() without an object
	// But making that static just causes other problems
	public static String getStaticPacketChannel() {
		return "Monumenta.Bungee.Error.Forward";
	}

	@Override
	public String getPacketChannel() {
		return "Monumenta.Bungee.Error.Forward";
	}

	@Override
	public String getPacketData() throws Exception {
		throw new Exception("This packet is generated by bungeecord!");
	}

	public static void handlePacket(Plugin plugin, String data) throws Exception {
		String[] rcvStrings = PacketUtils.decodeStrings(data);
		if (rcvStrings == null || rcvStrings.length == 0) {
			throw new Exception("Received string data is null or invalid length");
		}
	}
}
